{% set name = "odc-algo" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: cf5dd82a18b49c9983fadf1482e173770bee1eae647c2e2fcf1d0eb799b0306c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - affine
    - dask-core
    - dask-image
    - datacube >=1.8.5
    - distributed
    - numexpr
    - numpy
    - rasterio >=1.3.2
    - scikit-image
    - toolz
    - xarray

test:
  imports:
    - odc.algo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opendatacube/odc-tools/
  summary: Miscellaneous Algorithmic helper methods
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - Kirill888
