{% set name = "odc-algo" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/odc-algo-{{ version }}.tar.gz
  sha256: 1cb49389d282bf4b8c08dc7eabb474b345c8110e8eadd52ee95874d80c7ed494

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - affine
    - dask-core
    - dask-image
    - datacube >=1.8.5
    - distributed
    - numexpr
    - numpy
    - rasterio
    - scikit-image
    - toolz
    - xarray

test:
  imports:
    - odc.algo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/opendatacube/odc-tools/
  summary: Miscellaneous Algorithmic helper methods
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - Kirill888
