{% set python_min = "3.10" %}

{% set name = "odc-algo" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 84f46df6edb3e2b3f86862e427f4fd1423f75dbea81e0e1223f0bb18b38d5194

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=69
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - affine
    - dask-core
    - dask-image
    - distributed <2025.4
    - numexpr
    - numpy
    - rasterio >=1.3.2
    - odc-geo
    - scikit-image
    - toolz
    - xarray
    - geomad

test:
  imports:
    - odc.algo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opendatacube/odc-tools/
  summary: Miscellaneous Algorithmic helper methods
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - Kirill888
